on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

name: ci-build
permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1
        with:
          versionSpec: '6.3.x'
          
      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v4.0.1
        with:
          updateProjectFiles: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal